### ISSUE TITLE
uninstall error

### ISSUE THREAD

**Issue by yaogang2018** [chaoleili/jupyterlab_tensorboard#3]
Because I cannot use this extension,it always says 404 when I click the Tensorboard card in the launcher,so I use `jupyter labextension uninstall jupyterlab_tensorboard `to uninstall it.
But then I can't launch jupyterlab,the brower is blank and there ia a warning:

> [W 20:12:56.063 LabApp] Error loading server extension jupyter_tensorboard
    Traceback (most recent call last):
      File "/home/yaogang/miniconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1481, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/yaogang/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_tensorboard'

What should I do then?

**Comment by yaogang2018** [comment]
If I run `jupyter lab --core-mode` in bash,then it's all right.

If I reinstall this extension,the http://localhost:8888/lab is also blank.

**Comment by chaoleili** [comment]
Well, jupyterlab_tensorboard need this project [jupyter_tensorboard](https://github.com/lspvic/jupyter_tensorboard) as [pre-request](https://github.com/chaoleili/jupyterlab_tensorboard#prerequisites). So we need install jupyter_tensorboard at first, that's why you got 404 error(no backend for tensorboard). You can also use `jupyter nbextension list` to check the jupyter_tensorboard info. If you uninstall the jupyterlab_tensorboard, please using `jupyter labextension list` to make sure the jupyterlab_tensorboard is already diasbaled or removed. if not, using `jupyter labextension disable jupyterlab_tensorboard` disable it and then launch your jupyterlab.  :)

**Comment by yaogang2018** [comment]
Thank you.
It seems I made a mistake.I have 2 conda environments,one is base,one is tensorflow, I install jupyter_tensorboard  in the tensorflow environment and not in the base environment, and my jupyterlab is in the base environment, so the base python cannot find jupyter_tensorboard to import. 
I just install jupyterlab in tensorflow environment, then there is nothing wrong.

Another little problem:Can you update to jupyterlab version 0.34,the icon style problem:

![icon](https://user-images.githubusercontent.com/12131589/45530401-00b19300-b81d-11e8-865c-a4dda5db5342.png)
